package com.DTEC.Document_Tracking_and_E_Clearance.user;

public enum Role {
    SUPER_ADMIN,
    ADMIN,
    PERSONNEL,
    MODERATOR,
    STUDENT,
    STUDENT_OFFICER,
    DSA,
    PRESIDENT,
    COMMUNITY,
    FINANCE,
    OFFICE_HEAD,

    GUIDANCE,
    DEAN,
    CASHIER,
    LIBRARIAN,
    SCHOOL_NURSE,
    PROGRAM_HEAD,
    REGISTRAR,

    SCIENCE_LAB,
    COMPUTER_SCIENCE_LAB,
    ELECTRONICS_LAB,
    CRIM_LAB,
    HRM_LAB,
    NURSING_LAB,

    ACCOUNTING_CLERK,
    CUSTODIAN,
    VPAF,
    VPA,
    MULTIMEDIA
}
